# Fetching latest version of Java
FROM ubuntu:17
 
# Setting up work directory
WORKDIR /app

# Copy the jar file into our app
COPY ./target/todolist-1.0.0.jar /app

# Exposing port 8080
EXPOSE 8080

# Starting the application
CMD ["java", "-jar", "todolist-1.0.0.jar"]